### PR TITLE
Allow urls with basic http auth.

### PR DESCRIPTION
**Pull request by ThinkTransit**
Great project Glenn,

Would you consider a small addition to allow basic http auth?

### CODE REVIEW

**Comment by glenn20** [comment]
@ThinkTransit - I'm so sorry I missed the notification for this PR. I had an extended break in dec-jan and lost a few messages in thne backlog when I got back. This is a very good addition. I will review the PR shortly.

Thanks for this very useful contribution.

**Comment by glenn20** [comment]
Merged. Thanks again for the contribution.

**Comment by ThinkTransit** [comment]
Thanks @glenn20 hope you had a nice break.

**Comment by glenn20** [comment]
@ThinkTransit - I am thinking of changing the api for this feature to:

- function `ota.update.from_file(url: str, sha="", length=0, verify=True,
  verbose=True, reboot=True, **request_args)`

  Read a micropython firmware from url and write it to the next ota partition.
  sha and length are used to validate the data written to the partition.
  Returns the number of bytes written to the partition.

  - `url` is a http[s] url or a filename on the device
  - `sha` (optional) is the expected sha256sum of the firmware file
  - `length` (optional) is the expected length of the firmware file (in bytes)
  - `verify=True` (optional) Read back the data written to the flash storage and
    veryify the sha256sum checksum.
  - `verbose=True` (optional) prints out verbose information of what it is doing
  - `reboot=True` (optional) Performs a `machine.hard_reset()` 10 seconds after
    a successful OTA update.
  - `request_args`: any additional keyword arguments will be passed as
    keyword arguments to `requests.get()`, eg:
    - `ota.update.from_file("http://nas.local/micropython.bin",
      auth=("username", "password"))`.

The goal is to provide more flexibility to allow users to pass through any options to the `requests.get()` call.

 I would be interested if you have any concerns with this change or if it will complicate your workflow.

**Comment by ThinkTransit** [comment]
Looks like a much cleaner option @glenn20

**Pull request merged**
